apiVersion: v1
kind: Service
metadata:
  name: {{ include "websocket-server.fullname" . }}
  labels:
    app: {{ include "websocket-server.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "websocket-server.name" . }}
  type: ClusterIP
